### ISSUE TITLE
PWM D13 led

### ISSUE THREAD

**Issue by wifixcort** [sparkfun/SAMD21_Mini_Breakout#7]
Hi, I'm currently testing this Mini board and I maybe find a strange behavior.
With your example in this page https://learn.sparkfun.com/tutorials/samd21-minidev-breakout-hookup-guide/setting-up-arduino.

When I upload the sketch  the led 13 does not fade. If I change the board from Mini to Dev board all good.

**Comment by jimblom** [comment]
This is an unfortunate side effect of equipping pins 10-13 on the Mini with SPI support (compare the [Mini's pin 13 declaration](https://github.com/sparkfun/Arduino_Boards/blob/master/sparkfun/samd/variants/SparkFun_SAMD_Mini/variant.cpp#L137) to the [Dev/Zero's](https://github.com/sparkfun/Arduino_Boards/blob/master/sparkfun/samd/variants/arduino_zero/variant.cpp#L137)). The pin's peripheral is, at least initially, muxed to SERCOM instead of a timer.

The [pinPeripheral function](https://github.com/sparkfun/Arduino_Boards/blob/master/sparkfun/samd/cores/arduino/wiring_private.c#L22) can be used to change a pin's mux, but it's not publicly available to the Arduino sketch. Adding **`#include "wiring_private.h"`** to the top of the sketch, and throwing **`pinPeripheral(13, PIO_TIMER);`** at the start of `setup()` isn't pretty, but it works.

Thanks for the letting us know about this. I'll make a note in the tutorial.

**Comment by drewfish** [comment]
Yeah, I desoldered the LED 13 from my Mini so that SPI traffic wouldn't light it up (and eat battery power).

**Comment by ianccole** [comment]
I think it's not enough to re-program the port mux  - you also need to modify g_APinDescription for the specified pin.

analogWrite() uses g_APinDescription to control it's action

**Comment by ianccole** [comment]
> This is an unfortunate side effect of equipping pins 10-13 on the Mini with SPI support (compare the [Mini's pin 13 declaration](https://github.com/sparkfun/Arduino_Boards/blob/master/sparkfun/samd/variants/SparkFun_SAMD_Mini/variant.cpp#L137) to the [Dev/Zero's](https://github.com/sparkfun/Arduino_Boards/blob/master/sparkfun/samd/variants/arduino_zero/variant.cpp#L137)). The pin's peripheral is, at least initially, muxed to SERCOM instead of a timer.
> 
> The [pinPeripheral function](https://github.com/sparkfun/Arduino_Boards/blob/master/sparkfun/samd/cores/arduino/wiring_private.c#L22) can be used to change a pin's mux, but it's not publicly available to the Arduino sketch. Adding **`#include "wiring_private.h"`** to the top of the sketch, and throwing **`pinPeripheral(13, PIO_TIMER);`** at the start of `setup()` isn't pretty, but it works.
> 
> Thanks for the letting us know about this. I'll make a note in the tutorial.

I think it's not enough to re-program the port mux - you also need to modify g_APinDescription for the specified pin.

analogWrite() uses g_APinDescription to control it's action
